## NANCY TRUONG

09/09/2025

# Local simple regression

Write your own function for performing predictions with Local Regression using one predictor.

The input arguments to the function must be

 - y a vector of observations of the response variable
cd
 - x a vector of observations of the predictor
 - k the number of neighboring points to include in each local regression and
 - x_0 a vector of values for which a prediction is going to be made

The function shall return

- pred a vector of predicted values, and

- se a vector of standard deviations of the expected value of each predicted value

In [17]:
# import libraries
import numpy as np
import pandas as pd

print("Import libraries sucessfully")

Import libraries sucessfully


In [18]:
dummy = [3,1,0]
sorted(dummy)[:2]

[0, 1]

In [19]:
class LocalRegression():
    def __init__(self, X, Y):
        self.X = np.array(X)
        self.Y = np.array(Y)
    def local_regression(self,x0, k):
        """
        X: vector of obs of predictor
        Y: vector of obs of response
        x0: vector values for which a prediction is going to made
        k: number of nearest neighbors    
        """
        # add first row 1 for the intercept theta_0
        #x0 = np.array(x0)
        if isinstance(x0, (int, float)):
            x0 = np.array([x0])  # convert to 1D array with 1 element

        
        # Solving the OLS
        #print(X_weights)
        x0 = np.r_[1, x0]
        #x0 = [1,x0]
        X = np.c_[np.ones(len(self.X)), self.X]
        k_X = X[:k]
        k_Y = self.Y[:k]
        X_weights = k_X.T @ self.weight_func(X,x0, k=k)
        thetas = np.linalg.pinv(X_weights @ k_X) @ X_weights @ k_Y
        #print("X = ", X)
        print("Estimated parameters: ",thetas)
        pred = x0 @ thetas
        residuals = self.Y - X @ thetas 
        sigma_2_est = (residuals @ residuals) / (X.shape[0] - X.shape[1])
        se = np.sqrt(sigma_2_est * (x0 @ np.linalg.pinv(X_weights @ k_X) @ x0))
        return pred, se
    def weight_func(self, X,x0, k):
        weights = []
        distances = []
        for row in X:
            eucl_distance = np.linalg.norm(row - x0)
            distances.append(1/eucl_distance)
        distances = sorted(distances)[:k]
        distances_inv = [1/d for d in distances]
        return np.diag(distances_inv)


In [20]:
x= np.array([1])
print(x.ndim)


1


In [21]:
X_mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(X_mat[:2])

[[1 2 3]
 [4 5 6]]


In [22]:
X = np.array([1,2,3])
np.diag(X)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [23]:
df_original = pd.read_csv('/Users/mexmex/Documents/3-Math_LU/HT2025/BERN02/Exercise 3/Data/pollution_cleaneddata.csv')
df_original.head()

PREC  JANT  JULT  OVR65  POPN  EDUC  HOUS    DENS  NONW  WWDRK  POOR    HC  \
0  36.0  27.0  71.0    8.1  3.34  11.4  81.5  3243.0   8.8   42.6  11.7  21.0   
1  35.0  23.0  72.0   11.1  3.14  11.0  78.8  4281.0   3.5   50.7  14.4   8.0   
2  44.0  29.0  74.0   10.4  3.21   9.8  81.6  4260.0   0.8   39.4  12.4   6.0   
3  47.0  45.0  79.0    6.5  3.41  11.1  77.5  3125.0  27.1   50.2  20.6  18.0   
4  43.0  35.0  77.0    7.6  3.44   9.6  84.6  6441.0  24.4   43.7  14.3  43.0   

    NOX    SO@  HUMID      MORT  
0  15.0   59.0   59.0   921.870  
1  10.0   39.0   57.0   997.875  
2   6.0   33.0   54.0   962.354  
3   8.0   24.0   56.0   982.291  
4  38.0  206.0   55.0  1071.289

In [24]:
df_meta = open('/Users/mexmex/Documents/3-Math_LU/HT2025/BERN02/Exercise 3/Data/pollution_metadata.txt')
print(df_meta.read())

This is the pollution data so loved by writers of papers on ridge regression.
Source: McDonald, G.C. and Schwing, R.C. (1973) 'Instabilities of regression
estimates relating air pollution to mortality', Technometrics, vol.15, 463-
482.
Variables in order:
PREC   Average annual precipitation in inches
JANT   Average January temperature in degrees F
JULT   Same for July
OVR65  % of 1960 SMSA population aged 65 or older
POPN   Average household size
EDUC   Median school years completed by those over 22
HOUS   % of housing units which are sound & with all facilities
DENS   Population per sq. mile in urbanized areas, 1960
NONW   % non-white population in urbanized areas, 1960
WWDRK  % employed in white collar occupations
POOR   % of families with income < $3000
HC     Relative hydrocarbon pollution potential
NOX    Same for nitric oxides
SO@    Same for sulphur dioxide
HUMID  Annual average % relative humidity at 1pm
MORT   Total age-adjusted mortality rate per 100,000

36.     27.     71. 

Predict Total age-adjusted mortality rate per 100,000 (MORT) for an area with 10, 18 and 25 % of families with income < $3000 (POOR)

x0:

POOR = 10

POOR = 18

POOR = 25

In [25]:
df = df_original.copy()
df.shape

(60, 16)

In [26]:
X_cov = df['POOR'].values
#X_cov = X_cov - np.mean(X_cov)

In [27]:
Y_resp = df['MORT'].values
Y_resp.shape

(60,)

In [28]:
model0 = LocalRegression(X_cov, Y_resp)
model0

In [29]:
pred_10, se_10= model0.local_regression(x0=10, k=15)
print(f"Prediction POOR = 10: {pred_10}, SE = {se_10}")

Estimated parameters:  [906.78590062   4.85310227]
Prediction POOR = 10: 955.3169232672024, SE = 7.998242054183074


In [30]:
pred_18, se_18= model0.local_regression(x0=18, k=15)
print(f"Prediction POOR = 18: {pred_18}, SE = {se_18}")

Estimated parameters:  [909.84314994   4.62102302]
Prediction POOR = 18: 993.0215642429034, SE = 7.731670322101022


In [31]:
pred_25, se_25= model0.local_regression(x0=25, k=15)
print(f"Prediction POOR = 25: {pred_25}, SE = {se_25}")

Estimated parameters:  [909.94868822   4.6038206 ]
Prediction POOR = 25: 1025.0442031843063, SE = 11.222477649542352


In [32]:
df

PREC  JANT  JULT  OVR65  POPN  EDUC  HOUS    DENS  NONW  WWDRK  POOR  \
0   36.0  27.0  71.0    8.1  3.34  11.4  81.5  3243.0   8.8   42.6  11.7   
1   35.0  23.0  72.0   11.1  3.14  11.0  78.8  4281.0   3.5   50.7  14.4   
2   44.0  29.0  74.0   10.4  3.21   9.8  81.6  4260.0   0.8   39.4  12.4   
3   47.0  45.0  79.0    6.5  3.41  11.1  77.5  3125.0  27.1   50.2  20.6   
4   43.0  35.0  77.0    7.6  3.44   9.6  84.6  6441.0  24.4   43.7  14.3   
5   53.0  45.0  80.0    7.7  3.45  10.2  66.8  3325.0  38.5   43.1  25.5   
6   43.0  30.0  74.0   10.9  3.23  12.1  83.9  4679.0   3.5   49.2  11.3   
7   45.0  30.0  73.0    9.3  3.29  10.6  86.0  2140.0   5.3   40.4  10.5   
8   36.0  24.0  70.0    9.0  3.31  10.5  83.2  6582.0   8.1   42.5  12.6   
9   36.0  27.0  72.0    9.5  3.36  10.7  79.3  4213.0   6.7   41.0  13.2   
10  52.0  42.0  79.0    7.7  3.39   9.6  69.2  2302.0  22.2   41.3  24.2   
11  33.0  26.0  76.0    8.6  3.20  10.9  83.4  6122.0  16.3   44.9  10.7   
12  40.0  34.0  77.0    9.2  3.21  10.2  77.0  4101.0  13.0   45.7  15.1   
13  35.0  28.0  71.0    8.8  3.29  11.1  86.3  3042.0  14.7   44.6  11.4   
14  37.0  31.0  75.0    8.0  3.26  11.9  78.4  4259.0  13.1   49.6  13.9   
15  35.0  46.0  85.0    7.1  3.22  11.8  79.9  1441.0  14.8   51.2  16.1   
16  36.0  30.0  75.0    7.5  3.35  11.4  81.9  4029.0  12.4   44.0  12.0   
17  15.0  30.0  73.0    8.2  3.15  12.2  84.2  4824.0   4.7   53.1  12.7   
18  31.0  27.0  74.0    7.2  3.44  10.8  87.0  4834.0  15.8   43.5  13.6   
19  30.0  24.0  72.0    6.5  3.53  10.8  79.5  3694.0  13.1   33.8  12.4   
20  31.0  45.0  85.0    7.3  3.22  11.4  80.7  1844.0  11.5   48.1  18.5   
21  31.0  24.0  72.0    9.0  3.37  10.9  82.8  3226.0   5.1   45.2  12.3   
22  42.0  40.0  77.0    6.1  3.45  10.4  71.8  2269.0  22.7   41.4  19.5   
23  43.0  27.0  72.0    9.0  3.25  11.5  87.1  2909.0   7.2   51.6   9.5   
24  46.0  55.0  84.0    5.6  3.35  11.4  79.7  2647.0  21.0   46.9  17.9   
25  39.0  29.0  75.0    8.7  3.23  11.4  78.6  4412.0  15.6   46.6  13.2   
26  35.0  31.0  81.0    9.2  3.10  12.0  78.3  3262.0  12.6   48.6  13.9   
27  43.0  32.0  74.0   10.1  3.38   9.5  79.2  3214.0   2.9   43.7  12.0   
28  11.0  53.0  68.0    9.2  2.99  12.1  90.6  4700.0   7.8   48.9  12.3   
29  30.0  35.0  71.0    8.3  3.37   9.9  77.4  4474.0  13.1   42.6  17.7   
30  50.0  42.0  82.0    7.3  3.49  10.4  72.5  3497.0  36.7   43.3  26.4   
31  60.0  67.0  82.0   10.0  2.98  11.5  88.6  4657.0  13.5   47.3  22.4   
32  30.0  20.0  69.0    8.8  3.26  11.1  85.4  2934.0   5.8   44.0   9.4   
33  25.0  12.0  73.0    9.2  3.28  12.1  83.1  2095.0   2.0   51.9   9.8   
34  45.0  40.0  80.0    8.3  3.32  10.1  70.3  2682.0  21.0   46.1  24.1   
35  46.0  30.0  72.0   10.2  3.16  11.3  83.2  3327.0   8.8   45.3  12.2   
36  54.0  54.0  81.0    7.4  3.36   9.7  72.8  3172.0  31.4   45.5  24.2   
37  42.0  33.0  77.0    9.7  3.03  10.7  83.5  7462.0  11.3   48.7  12.4   
38  42.0  32.0  76.0    9.1  3.32  10.5  87.5  6092.0  17.5   45.3  13.2   
39  36.0  29.0  72.0    9.5  3.32  10.6  77.6  3437.0   8.1   45.5  13.8   
40  37.0  38.0  67.0   11.3  2.99  12.0  81.5  3387.0   3.6   50.3  13.5   
41  42.0  29.0  72.0   10.7  3.19  10.1  79.5  3508.0   2.2   38.8  15.7   
42  41.0  33.0  77.0   11.2  3.08   9.6  79.9  4843.0   2.7   38.6  14.1   
43  44.0  39.0  78.0    8.2  3.32  11.0  79.9  3768.0  28.6   49.5  17.5   
44  32.0  25.0  72.0   10.9  3.21  11.1  82.5  4355.0   5.0   46.4  10.8   
45  34.0  32.0  79.0    9.3  3.23   9.7  76.8  5160.0  17.2   45.1  15.3   
46  10.0  55.0  70.0    7.3  3.11  12.1  88.9  3033.0   5.9   51.0  14.0   
47  18.0  48.0  63.0    9.2  2.92  12.2  87.7  4253.0  13.7   51.2  12.0   
48  13.0  49.0  68.0    7.0  3.36  12.2  90.7  2702.0   3.0   51.9   9.7   
49  35.0  40.0  64.0    9.6  3.02  12.2  82.5  3626.0   5.7   54.3  10.1   
50  45.0  28.0  74.0   10.6  3.21  11.1  82.6  1883.0   3.4   41.9  12.3   
51  38.0  24.0  72.0    9.8  3.34  11.4  78.0  4923.